# Generated by Django 5.2.5 on 2025-08-11 13:58

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
