# Generated by Django 5.2.5 on 2025-08-11 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sentinel', '0002_auto_20250811_1558'),
    ]

    operations = [migrations.RunSQL(
        """
        CREATE TEXT SEARCH CONFIGURATION french_unaccent( COPY = french );
        ALTER TEXT SEARCH CONFIGURATION french_unaccent
        ALTER MAPPING FOR hword, hword_part, word
        WITH unaccent, french_stem;
        """
    )
    ]
