# Generated by Django 5.2.8 on 2026-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_cartocompany_is_dormant'),
    ]

    operations = [
        migrations.AddField(
            model_name='departementscomputation',
            name='graph_cumul',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='francecomputation',
            name='graph_cumul',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='installationscomputation',
            name='graph_cumul',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='regionscomputation',
            name='graph_cumul',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
