# Generated by Django 5.2.8 on 2026-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcontrol', '0003_alter_bsdpdf_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbundle',
            name='request_type',
            field=models.CharField(choices=[('ROAD_CONTROL', 'Road control'), ('BSD', 'Bsd')], default='ROAD_CONTROL', max_length=20, verbose_name='Request Type'),
        ),
    ]
