# Generated by Django 5.2.8 on 2026-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcontrol', '0004_pdfbundle_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbundle',
            name='search_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
