# Generated by Django 5.2.8 on 2026-06-05 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcontrol', '0005_pdfbundle_search_params'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bsdpdf',
            name='roadcontrol_request_9ad607_idx',
        ),
        migrations.RemoveField(
            model_name='bsdpdf',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='pdfbundle',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='bsdpdf',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadcontrol_bsdpdfs', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='pdfbundle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadcontrol_pdfbundles', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
