# Generated by Django 5.2.6 on 2025-10-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0066_computedinspectiondata_company_has_enabled_registry_dnd_from_bsd_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='bsd_refused_data',
            field=models.JSONField(default=dict),
        ),
    ]
