# Generated by Django 5.2.8 on 2026-01-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0067_computedinspectiondata_bsd_refused_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedinspectiondata',
            name='eco_organisme_partners_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='computedinspectiondata',
            name='is_vhu_company',
            field=models.BooleanField(default=False),
        ),
    ]
