# Generated by Django 5.2.5 on 2025-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_registryv2export_export_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryv2export',
            name='registry_type',
            field=models.CharField(choices=[('INCOMING', 'Registre entrant'), ('MANAGED', 'Registre des courtiers/négociants'), ('OUTGOING', 'Registre sortant'), ('SSD', 'Registre Sortie de statut de déchet'), ('TRANSPORTED', 'Registre des transporteurs')], default='INCOMING', max_length=20, verbose_name='Type de registre'),
        ),
    ]
