# Generated by Django 5.2.8 on 2026-06-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_registryv2exportsiren_registryv2exportsiret'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registryv2exportsiren',
            new_name='registry_re_siren_fea29e_idx',
            old_name='registry_re_siren_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='registryv2exportsiren',
            new_name='registry_re_state_07af51_idx',
            old_name='registry_re_state_def456_idx',
        ),
        migrations.RenameIndex(
            model_name='registryv2exportsiret',
            new_name='registry_re_parent__2e6859_idx',
            old_name='registry_re_parent__ghi789_idx',
        ),
        migrations.RenameIndex(
            model_name='registryv2exportsiret',
            new_name='registry_re_siret_d0ff6c_idx',
            old_name='registry_re_siret_jkl012_idx',
        ),
        migrations.AlterField(
            model_name='registryv2exportsiret',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siret_exports', to='registry.registryv2exportsiren'),
        ),
    ]
