# Generated by Django 5.2.8 on 2026-06-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordereau', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsdpdf',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='bsdpdf',
            name='company_contact',
        ),
        migrations.RemoveField(
            model_name='bsdpdf',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='bsdpdf',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='bsdpdf',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='bsdpdf',
            name='company_siret',
        ),
        migrations.RemoveField(
            model_name='bsdpdf',
            name='transporter_plate',
        ),
        migrations.RemoveField(
            model_name='pdfbundle',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='pdfbundle',
            name='company_contact',
        ),
        migrations.RemoveField(
            model_name='pdfbundle',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='pdfbundle',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='pdfbundle',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='pdfbundle',
            name='company_siret',
        ),
        migrations.RemoveField(
            model_name='pdfbundle',
            name='transporter_plate',
        ),
    ]
