# Generated by Django 5.2.8 on 2026-06-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordereau', '0002_remove_bsdpdf_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsdpdf',
            name='weight',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Weight'),
        ),
    ]
