# Generated by Django 5.2.7 on 2025-11-19 16:13

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [TrigramExtension(), UnaccentExtension()]
