# Generated by Django 5.2.7 on 2025-11-20 10:01

import django.db.models.deletion
import django_jsonform.models.fields
import mptt.fields
from django.db import migrations, models

import config.storage_backends
import faq.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('user_categories', django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('STAFF_TD', 'Staff Trackdéchets'), ('ADMINISTRATION_CENTRALE', 'Administration centrale'), ('INSPECTEUR_ICPE', 'Inspecteur ICPE'), ('CTT', 'CTT - Contrôleur des transports routiers'), ('INSPECTION_TRAVAIL', 'Inspection du travail'), ('GENDARMERIE', 'Gendarmerie'), ('ARS', 'ARS'), ('DOUANE', 'Douane'), ('OBSERVATOIRE', 'Observatoire')], max_length=32), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faq.faqpage')),
            ],
            options={
                'verbose_name': 'Page de faq',
                'verbose_name_plural': 'Pages de faq',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, max_length=512, storage=config.storage_backends.PrivateMediaStorage(), upload_to=faq.models.image_path, verbose_name='Image')),
                ('video_source', models.URLField(blank=True, max_length=512, verbose_name='Video url')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='faq.faqpage')),
            ],
            options={
                'verbose_name': 'Content block',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested', to='faq.faqpage')),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='faq.faqpage')),
            ],
            options={
                'verbose_name': 'Suggested Page',
                'ordering': ['order'],
            },
        ),
    ]
