# Generated by Django 5.2.7 on 2025-11-20 15:00

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Bloc de faq', 'verbose_name_plural': 'Blocs de faq'},
        ),
        migrations.CreateModel(
            name='AssistancePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link_anchor', models.CharField(blank=True, help_text='Override Title to display as link', max_length=200, verbose_name='Link Anchor')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('display_contact_form', models.CharField(choices=[('NO', 'Aucun'), ('CLOSED', 'Fermé'), ('OPEN', 'Ouvert')], default='NO', max_length=6, verbose_name='Affichage du formulaire de contact')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faq.assistancepage')),
            ],
            options={
                'verbose_name': "Page d'Assistance",
                'verbose_name_plural': "Pages d'Assistance",
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.TextField(blank=True, verbose_name='Objet du message')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('origin_page_title', models.CharField(blank=True, max_length=250, verbose_name="Page d'appel du formulaire")),
                ('origin_page_id', models.UUIDField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created'],
            },
        ),
    ]
