# Generated by Django 5.2.7 on 2025-11-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_contentblock_options_assistancepage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='origin_page_id',
        ),
    ]
