# Generated by Django 5.2.8 on 2025-11-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_webinar_alter_contentblock_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webinar',
            options={'ordering': ('-scheduled_at',), 'verbose_name': 'Webinaire', 'verbose_name_plural': 'Webinaires'},
        ),
    ]
