# Generated by Django 5.2.8 on 2025-12-03 09:09

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_alter_webinar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='user_categories',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(choices=[('STAFF_TD', 'Staff Trackdéchets'), ('ADMINISTRATION_CENTRALE', 'Administration centrale'), ('INSPECTEUR_ICPE', 'Inspecteur ICPE'), ('CTT', 'CTT - Contrôleur des transports routiers'), ('INSPECTION_TRAVAIL', 'Inspection du travail'), ('GENDARMERIE', 'Gendarmerie'), ('ARS', 'ARS'), ('DOUANE', 'Douane'), ('OBSERVATOIRE', 'Observatoire')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
