# Generated by Django 5.2.8 on 2025-12-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_alter_faqpage_user_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='slug',
        ),
    ]
