# Generated by Django 5.2.4 on 2025-08-04 15:19

import uuid

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NafCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='french'), output_field=django.contrib.postgres.search.SearchVectorField())),
            ],
            options={
                'verbose_name': 'Naf code',
                'verbose_name_plural': 'Naf codes',
            },
        ),
    ]
