# Generated by Django 5.2.4 on 2025-08-04 15:25

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naf', '0002_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='nafcode',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=512, editable=False, null=True),
        ),
    ]
