# Generated by Django 5.2.4 on 2025-08-04 16:13

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naf', '0003_nafcode_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nafcode',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024, editable=False, null=True),
        ),
    ]
