# Generated by Django 5.2.4 on 2025-08-04 16:34

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naf', '0004_alter_nafcode_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nafcode',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='embedding_idxx', opclasses=['vector_cosine_ops']),
        ),
    ]
