# Generated by Django 5.2.7 on 2025-11-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='welcome_content',
            field=models.TextField(blank=True, verbose_name="Texte affiché sur le bandeau de la page d'accueil"),
        ),
    ]
