# Generated by Django 5.2.8 on 2025-11-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_siteconfiguration_welcome_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='banner_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], default='info', max_length=20, verbose_name="Bannière d'information - type"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='welcome_content_connected',
            field=models.TextField(blank=True, verbose_name="Texte affiché sur le bandeau de la page d'accueil après connexion"),
        ),
    ]
