# Generated by Django 5.2.7 on 2025-11-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_exports', '0002_dataexportdownload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataexport',
            old_name='bsd_type',
            new_name='export_type',
        ),
        migrations.RenameField(
            model_name='dataexportdownload',
            old_name='bsd_type',
            new_name='export_type',
        ),
    ]
