# Generated by Django 5.2.7 on 2025-11-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_exports', '0003_rename_bsd_type_dataexport_export_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexport',
            name='export_type',
            field=models.CharField(choices=[('BSDD', 'Déchets dangereux'), ('BSDA', 'Amiante'), ('BSDASRI', 'DASRI'), ('BSVHU', 'VHU'), ('BSFF', 'Fluides Frigo'), ('DND_ENTRANT', 'Registre entrant : Déchets non dangereux'), ('DND_SORTANT', 'Registre sortant : Déchets non dangereux'), ('TEXS_ENTRANT', 'Registre entrant : Terres et sédiments'), ('TEXS_SORTANT', 'Registre sortant : Terres et sédiments')], max_length=20, verbose_name='Export Type'),
        ),
        migrations.AlterField(
            model_name='dataexportdownload',
            name='export_type',
            field=models.CharField(max_length=20, verbose_name='Export Type'),
        ),
    ]
