# Generated by Django 5.2.8 on 2026-02-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_exports', '0004_alter_dataexport_export_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexport',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Size'),
        ),
    ]
